language: node_js
node_js:
- "0.12"
- "0.10"
- iojs
before_install:
- npm install -g npm@'>2.7.0'
after_script:
- CODECLIMATE_REPO_TOKEN=7b0cbee1382c968a036868d26ec04d0ddc7b7aeef25ceead5ff9ff50a3c2ae8b codeclimate < coverage/lcov.info
- rm -rf ./coverage
notifications:
  email:
    on_success: change
    on_failure: change
